# Generated by Django 5.0.1 on 2024-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.CharField(db_index=True, max_length=3, verbose_name='Operator code')),
                ('bottom_limit', models.CharField(db_index=True, max_length=7, verbose_name='Bottom limit')),
                ('top_limit', models.CharField(db_index=True, max_length=7, verbose_name='Bottom limit')),
                ('operator_name', models.CharField(max_length=255, verbose_name='Operator name')),
                ('region', models.CharField(max_length=255, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'PhoneInfo',
                'verbose_name_plural': 'PhoneInfo',
            },
        ),
    ]
