# Generated by Django 5.0.1 on 2024-02-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinfo',
            name='bottom_limit',
            field=models.IntegerField(db_index=True, verbose_name='Bottom limit'),
        ),
        migrations.AlterField(
            model_name='phoneinfo',
            name='operator_code',
            field=models.IntegerField(db_index=True, verbose_name='Operator code'),
        ),
        migrations.AlterField(
            model_name='phoneinfo',
            name='top_limit',
            field=models.IntegerField(db_index=True, verbose_name='Bottom limit'),
        ),
    ]
